In [1]:
import pandas as pd
import numpy as np
import requests
import json
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
cosine_similarity(np.array([4,0,5,3,5,0,0]).reshape(1,-1),\
                  np.array([0,4,0,4,0,5,0]).reshape(1,-1))

array([[ 0.18353259]])

In [3]:
cosine_similarity(np.array([4,0,5,3,5,0,0]).reshape(1,-1),\
                  np.array([2,0,2,0,1,0,0]).reshape(1,-1))

array([[ 0.88527041]])

In [4]:
cosine_similarity(np.array([-.25,0,.75,-1.25,.75,0,0])\
                  .reshape(1,-1),\
                  np.array([0,-.33,0,-.33,0,.66,0])\
                  .reshape(1,-1))

array([[ 0.30772873]])

In [5]:
cosine_similarity(np.array([-.25,0,.75,-1.25,.75,0,0])\
                  .reshape(1,-1),\
                  np.array([.33,0,.33,0,-.66,0,0])\
                  .reshape(1,-1))

array([[-0.24618298]])

In [6]:
user_x = [0,.33,0,-.66,0,33,0]
user_y = [0,0,0,-1,0,.5,.5]

cosine_similarity(np.array(user_x).reshape(1,-1),\
                  np.array(user_y).reshape(1,-1))

array([[ 0.42447212]])

In [7]:
user_x = [0,.33,0,-.66,0,33,0]
user_z = [0,-.125,0,-.625,0,.375,.375]

cosine_similarity(np.array(user_x).reshape(1,-1),\
                  np.array(user_z).reshape(1,-1))

array([[ 0.46571861]])

In [8]:
s1 = [-1.0,0.0,0.0,0.0,1.0]
s2 = [-1.66,0.0,.33,0.0,1.33]

cosine_similarity(np.array(s1).reshape(1,-1),\
                  np.array(s2).reshape(1,-1))

array([[ 0.98221439]])

## Build a Recommendation Engine

In [519]:
myun = 'YOUR_USERNAME'
mypw = 'YOUR_USER_TOKEN'

### Get the repos I have starred

In [10]:
my_starred_repos = []
def get_starred_by_me():
    resp_list = []
    last_resp = ''
    first_url_to_get = 'https://api.github.com/user/starred'
    first_url_resp = requests.get(first_url_to_get, auth=(myun,mypw))
    last_resp = first_url_resp
    resp_list.append(json.loads(first_url_resp.text))
    
    while last_resp.links.get('next'):
        next_url_to_get = last_resp.links['next']['url']
        next_url_resp = requests.get(next_url_to_get, auth=(myun,mypw))
        last_resp = next_url_resp
        resp_list.append(json.loads(next_url_resp.text))
        
    for i in resp_list:
        for j in i:
            msr = j['html_url']
            my_starred_repos.append(msr)

In [11]:
get_starred_by_me()

In [388]:
my_starred_repos

['https://github.com/pydata/pandas',
 'https://github.com/ipython/ipywidgets',
 'https://github.com/tweepy/tweepy',
 'https://github.com/matplotlib/matplotlib',
 'https://github.com/d3/d3',
 'https://github.com/JohnLangford/vowpal_wabbit',
 'https://github.com/tensorflow/tensorflow',
 'https://github.com/scikit-learn/scikit-learn',
 'https://github.com/chncyhn/flappybird-qlearning-bot',
 'https://github.com/josephmisiti/awesome-machine-learning',
 'https://github.com/vinta/awesome-python',
 'https://github.com/yawitzd/dsi-course-materials',
 'https://github.com/ujjwalkarn/DataSciencePython',
 'https://github.com/ga-students/DSI-SF-1',
 'https://github.com/ga-students/DAT-23-NYC',
 'https://github.com/generalassembly-studio/dsi-course-materials',
 'https://github.com/wdm0006/twitter-pandas',
 'https://github.com/ga-students/DS_HK_2',
 'https://github.com/podopie/DAT18NYC',
 'https://github.com/jmcarp/robobrowser',
 'https://github.com/Charging-Alot/SpeakEasy-AI',
 'https://github.com/bi

In [12]:
len(my_starred_repos)

86

In [13]:
my_starred_users = []
for ln in my_starred_repos:
    right_split = ln.split('.com/')[1]
    starred_usr = right_split.split('/')[0]
    my_starred_users.append(starred_usr)

In [14]:
my_starred_users

['pydata',
 'ipython',
 'tweepy',
 'matplotlib',
 'd3',
 'JohnLangford',
 'tensorflow',
 'scikit-learn',
 'chncyhn',
 'josephmisiti',
 'vinta',
 'yawitzd',
 'ujjwalkarn',
 'ga-students',
 'ga-students',
 'generalassembly-studio',
 'wdm0006',
 'ga-students',
 'podopie',
 'jmcarp',
 'Charging-Alot',
 'bikz05',
 'cemoody',
 'serkanyersen',
 'shutterstock',
 'kennethreitz',
 'dataproofer',
 'PMSI-AlignAlytics',
 'toddmotto',
 'NathanEpstein',
 'iamaziz',
 'dhamaniasad',
 'amontalenti',
 'misterGF',
 'matryer',
 'jonathanslenders',
 'lmcinnes',
 'Quartz',
 'wdm0006',
 'tensorflow',
 'CSNW',
 'coursera-dl',
 'twitter',
 'fivethirtyeight',
 'sloria',
 'mit-nlp',
 'grangier',
 'nicolaskruchten',
 'lukhnos',
 'jreback',
 'mikemull',
 'stitchfix',
 'bmtgoncalves',
 'hangtwenty',
 'rhiever',
 'minimaxir',
 'justmarkham',
 'niklasvh',
 'kennethreitz',
 'simple-statistics',
 'cchi',
 'yhat',
 'sandialabs',
 'bloomberg',
 'caesar0301',
 'zenorocha',
 'fent',
 'automl',
 'elastic',
 'szilard',
 'faso

In [15]:
len(my_starred_users)

86

### Looks like some duplication because I starred multiple repos for some users

In [16]:
len(set(my_starred_users))

79

### Now let's get the repos they starred

In [163]:
starred_repos = {k:[] for k in set(my_starred_users)}
def get_starred_by_user(user_name):
    starred_resp_list = []
    last_resp = ''
    first_url_to_get = 'https://api.github.com/users/'+ user_name +'/starred'
    first_url_resp = requests.get(first_url_to_get, auth=(myun,mypw))
    last_resp = first_url_resp
    starred_resp_list.append(json.loads(first_url_resp.text))
    
    while last_resp.links.get('next'):
        next_url_to_get = last_resp.links['next']['url']
        next_url_resp = requests.get(next_url_to_get, auth=(myun,mypw))
        last_resp = next_url_resp
        starred_resp_list.append(json.loads(next_url_resp.text))
        
    for i in starred_resp_list:
        for j in i:
            sr = j['html_url']
            starred_repos.get(user_name).append(sr)

In [164]:
for usr in list(set(my_starred_users)):
    print(usr)
    try:
        get_starred_by_user(usr)
    except:
        print('failed for user', usr)

pydata
podopie
twitter
grangier
bmtgoncalves
bloomberg
donnemartin
cchi
monkeylearn
misterGF
clips
hangtwenty
sandialabs
yhat
d3
vinta
shutterstock
matryer
lmcinnes
szilard
automl
mit-nlp
elastic
kennethreitz
dataproofer
paulgb
justmarkham
dhamaniasad
zenorocha
brandomr
iamaziz
NathanEpstein
caesar0301
jakevdp
tensorflow
sloria
CSNW
agermanidis
wdm0006
jreback
bikz05
yawitzd
simple-statistics
summanlp
ga-students
coursera-dl
scikit-learn
jonathanslenders
jmcarp
chncyhn
josephmisiti
amontalenti
ipython
stitchfix
datamade
mikemull
matplotlib
Quartz
fasouto
lensacom
jseabold
rhiever
minimaxir
fivethirtyeight
nicolaskruchten
tweepy
generalassembly-studio
derek73
niklasvh
serkanyersen
JohnLangford
fent
Charging-Alot
toddmotto
rushter
cemoody
PMSI-AlignAlytics
lukhnos
ujjwalkarn


In [165]:
len(starred_repos)

79

### Now we'll build a vocabulary that includes all the repos starred by the users I starred

In [166]:
repo_vocab = [item for sl in list(starred_repos.values()) for item in sl]

In [167]:
repo_set = list(set(repo_vocab))

In [391]:
len(repo_set)

12378

In [169]:
all_usr_vector = []
for k,v in starred_repos.items():
    usr_vector = []
    for url in repo_set:
        if url in v:
            usr_vector.extend([1])
        else:
            usr_vector.extend([0])
    all_usr_vector.append(usr_vector)

In [389]:
len(all_usr_vector)

79

In [171]:
df = pd.DataFrame(all_usr_vector, columns=repo_set, index=starred_repos.keys())

In [172]:
df

https://github.com/wagerfield/parallax  \
bmtgoncalves                                                 0   
twitter                                                      0   
matryer                                                      0   
bloomberg                                                    0   
donnemartin                                                  0   
cchi                                                         0   
monkeylearn                                                  0   
misterGF                                                     0   
clips                                                        0   
hangtwenty                                                   0   
sandialabs                                                   0   
JohnLangford                                                 0   
grangier                                                     0   
yhat                                                         0   
d3                                                           0   
vinta                                                        0   
szilard                                                      0   
podopie                                                      0   
paulgb                                                       0   
ujjwalkarn                                                   0   
automl                                                       0   
mit-nlp                                                      0   
elastic                                                      0   
kennethreitz                                                 0   
justmarkham                                                  0   
dhamaniasad                                                  1   
brandomr                                                     0   
jakevdp                                                      0   
pydata                                                       0   
coursera-dl                                                  0   
...                                                        ...   
ipython                                                      0   
minimaxir                                                    0   
datamade                                                     0   
mikemull                                                     0   
fent                                                         0   
matplotlib                                                   0   
fasouto                                                      1   
zenorocha                                                    0   
lensacom                                                     0   
jseabold                                                     0   
rhiever                                                      0   
serkanyersen                                                 0   
nicolaskruchten                                              0   
tweepy                                                       0   
caesar0301                                                   0   
iamaziz                                                      0   
generalassembly-studio                                       0   
stitchfix                                                    0   
derek73                                                      0   
niklasvh                                                     0   
NathanEpstein                                                0   
shutterstock                                                 0   
rushter                                                      0   
Charging-Alot                                                0   
Quartz                                                       0   
toddmotto                                                    0   
cemoody                                                      0   
PMSI-AlignAlytics                                            0   
lukhnos                                                      0  

In [390]:
len(df.columns)

12378

### Now I need to add myself to this dataframe to find the similarity between myself and the other users

In [174]:
my_repo_comp = []
for i in df.columns:
    if i in my_starred_repos:
        my_repo_comp.append(1)
    else:
        my_repo_comp.append(0)

In [175]:
mrc = pd.Series(my_repo_comp).to_frame(myun).T

In [176]:
mrc

0      1      2      3      4      5      6      7      8      9      \
acombs      0      0      0      0      0      0      0      0      0      0   

        ...    12368  12369  12370  12371  12372  12373  12374  12375  12376  \
acombs  ...        0      0      0      0      0      0      0      0      0   

        12377  
acombs      0  

[1 rows x 12378 columns]

In [177]:
mrc.columns = df.columns

In [178]:
fdf = pd.concat([df, mrc])

In [179]:
fdf

https://github.com/wagerfield/parallax  \
bmtgoncalves                                                 0   
twitter                                                      0   
matryer                                                      0   
bloomberg                                                    0   
donnemartin                                                  0   
cchi                                                         0   
monkeylearn                                                  0   
misterGF                                                     0   
clips                                                        0   
hangtwenty                                                   0   
sandialabs                                                   0   
JohnLangford                                                 0   
grangier                                                     0   
yhat                                                         0   
d3                                                           0   
vinta                                                        0   
szilard                                                      0   
podopie                                                      0   
paulgb                                                       0   
ujjwalkarn                                                   0   
automl                                                       0   
mit-nlp                                                      0   
elastic                                                      0   
kennethreitz                                                 0   
justmarkham                                                  0   
dhamaniasad                                                  1   
brandomr                                                     0   
jakevdp                                                      0   
pydata                                                       0   
coursera-dl                                                  0   
...                                                        ...   
minimaxir                                                    0   
datamade                                                     0   
mikemull                                                     0   
fent                                                         0   
matplotlib                                                   0   
fasouto                                                      1   
zenorocha                                                    0   
lensacom                                                     0   
jseabold                                                     0   
rhiever                                                      0   
serkanyersen                                                 0   
nicolaskruchten                                              0   
tweepy                                                       0   
caesar0301                                                   0   
iamaziz                                                      0   
generalassembly-studio                                       0   
stitchfix                                                    0   
derek73                                                      0   
niklasvh                                                     0   
NathanEpstein                                                0   
shutterstock                                                 0   
rushter                                                      0   
Charging-Alot                                                0   
Quartz                                                       0   
toddmotto                                                    0   
cemoody                                                      0   
PMSI-AlignAlytics                                            0   
lukhnos                                                      0   
fivethirtyeight                                              0  

In [192]:
l2 = my_starred_repos

In [194]:
l1 = fdf.iloc[-1,:][fdf.iloc[-1,:]==1].index.values

In [199]:
a = set(l1)
b = set(l2)

In [205]:
b.difference(a)

{'https://github.com/Charging-Alot/SpeakEasy-AI',
 'https://github.com/bikz05/bag-of-words',
 'https://github.com/cchi/viral-markov',
 'https://github.com/datamade/name-cleaver',
 'https://github.com/ga-students/DAT-23-NYC',
 'https://github.com/ga-students/DSI-SF-1',
 'https://github.com/ga-students/DS_HK_2',
 'https://github.com/generalassembly-studio/dsi-course-materials',
 'https://github.com/ipython/ipywidgets',
 'https://github.com/jakevdp/2013_fall_ASTR599',
 'https://github.com/jseabold/depy',
 'https://github.com/lukhnos/textrank-study-python',
 'https://github.com/mikemull/Notebooks',
 'https://github.com/minimaxir/video-to-gif-osx',
 'https://github.com/monkeylearn/twitter-post',
 'https://github.com/podopie/DAT18NYC',
 'https://github.com/serkanyersen/angular-circular-progress',
 'https://github.com/shutterstock/lil-brother',
 'https://github.com/summanlp/textrank',
 'https://github.com/wdm0006/twitter-pandas',
 'https://github.com/yawitzd/dsi-course-materials'}

In [206]:
from sklearn.metrics import jaccard_similarity_score
from scipy.stats import pearsonr

In [392]:
sim_score = {}
for i in range(len(fdf)):
    ss = pearsonr(fdf.iloc[-1,:], fdf.iloc[i,:])
    sim_score.update({i: ss[0]})

In [393]:
sf = pd.Series(sim_score).to_frame('similarity')

In [395]:
sf

similarity
0          NaN
1          NaN
2     0.007047
3          NaN
4     0.134539
5     0.164320
6          NaN
7     0.011832
8          NaN
9     0.037096
10         NaN
11    0.087020
12    0.021139
13         NaN
14         NaN
15    0.036319
16    0.046526
17    0.013933
18    0.037381
19    0.061026
20         NaN
21         NaN
22         NaN
23    0.000220
24    0.105784
25    0.030913
26   -0.002263
27    0.057448
28         NaN
29         NaN
..         ...
50    0.046087
51         NaN
52    0.024166
53   -0.001845
54         NaN
55    0.042504
56    0.000988
57         NaN
58    0.011952
59    0.072050
60   -0.005711
61   -0.001306
62         NaN
63    0.015225
64    0.111629
65         NaN
66         NaN
67    0.006731
68    0.018723
69    0.091494
70         NaN
71    0.149323
72         NaN
73         NaN
74    0.004779
75    0.015860
76         NaN
77   -0.003924
78         NaN
79    1.000000

[80 rows x 1 columns]

In [443]:
sf.sort_values('similarity', ascending=False)

similarity
79    1.000000
31    0.204703
5     0.164320
71    0.149323
4     0.134539
64    0.111629
24    0.105784
69    0.091494
11    0.087020
59    0.072050
37    0.070678
19    0.061026
27    0.057448
46    0.049183
16    0.046526
50    0.046087
34    0.044574
47    0.043064
55    0.042504
48    0.037967
18    0.037381
9     0.037096
15    0.036319
44    0.032272
25    0.030913
45    0.025943
52    0.024166
12    0.021139
32    0.020970
68    0.018723
..         ...
3          NaN
6          NaN
8          NaN
10         NaN
13         NaN
14         NaN
20         NaN
21         NaN
22         NaN
28         NaN
29         NaN
30         NaN
33         NaN
36         NaN
40         NaN
41         NaN
42         NaN
43         NaN
49         NaN
51         NaN
54         NaN
57         NaN
62         NaN
65         NaN
66         NaN
70         NaN
72         NaN
73         NaN
76         NaN
78         NaN

[80 rows x 1 columns]

In [453]:
fdf.index[5]

'cchi'

In [452]:
fdf.iloc[71,:][fdf.iloc[71,:]==1]

https://github.com/linkedin/FeatureFu                                                   1
https://github.com/pfnet/chainer                                                        1
https://github.com/mitsuhiko/python-regex-scanner                                       1
https://github.com/Jam3/math-as-code                                                    1
https://github.com/ipython/ipython                                                      1
https://github.com/scikit-learn-contrib/lightning                                       1
https://github.com/h2oai/h2o-2                                                          1
https://github.com/lorien/awesome-web-scraping                                          1
https://github.com/kennethreitz/requests                                                1
https://github.com/Theano/Theano                                                        1
https://github.com/quantopian/pyfolio                                                   1
https://gi

In [510]:
all_recs = fdf.iloc[[31,5,71,79],:][fdf.iloc[[31,5,71,79],:]==1].fillna(0).T

In [511]:
all_recs[(all_recs==1).all(axis=1)]

lmcinnes  cchi  rushter  acombs
https://github.com/tensorflow/skflow                 1     1        1       1
https://github.com/scikit-learn/scikit-learn         1     1        1       1

In [515]:
str_recs_tmp = all_recs[all_recs[myun]==0].copy()
str_recs = str_recs_tmp.iloc[:,:-1].copy()
str_recs

lmcinnes  cchi  rushter
https://github.com/wagerfield/parallax                     0     0        0
https://github.com/agibsonsw/AndyPython                    0     0        0
https://github.com/taion/scroll-behavior                   0     0        0
https://github.com/anicollection/anicollection             0     0        0
https://github.com/mahmoud/lithoxyl                        0     0        0
https://github.com/gciruelos/musthe                        0     0        0
https://github.com/slimkrazy/python-google-places          0     0        0
https://github.com/afgiel/video_cnn                        0     0        0
https://github.com/KristianOellegaard/packer-storm         0     0        0
https://github.com/carlsednaoui/ouibounce                  0     0        0
https://github.com/aljosa/django-tinymce                   0     0        0
https://github.com/mirumee/django-images                   0     0        0
https://github.com/Khan/KaTeX                              0     0        0
https://github.com/awslabs/ecs-refarch-service-...         0     0        0
https://github.com/skuroda/PackageResourceViewer           0     0        0
https://github.com/Netflix/SimianArmy                      0     0        0
https://github.com/nicolashery/mac-dev-setup               0     0        0
https://github.com/amueller/nyu_ml_lectures                0     0        0
https://github.com/imkevinxu/xkcdgraphs                    0     0        0
https://github.com/ReactiveX/RxJavaReactiveStreams         0     0        0
https://github.com/pengwynn/fumblr                         0     0        0
https://github.com/opengovernment/opengovernment           0     0        0
https://github.com/arkency/reactjs_koans                   0     0        0
https://github.com/reactjs/react-future                    0     0        0
https://github.com/dawenl/stochastic_PMF                   0     0        0
https://github.com/codrops/LineMenuStyles                  0     0        0
https://github.com/jinzhu/gorm                             0     0        0
https://github.com/wycats/jquery-offline                   0     0        0
https://github.com/andialbrecht/sqlparse                   0     0        0
https://github.com/django-compressor/django-app...         0     0        0
...                                                      ...   ...      ...
https://github.com/mbachry/exxo                            0     0        1
https://github.com/creationix/node-blog                    0     0        0
https://github.com/radar/guides                            0     0        0
https://github.com/dobarkod/typedecorator                  0     0        0
https://github.com/kalcaddle/KODExplorer                   0     0        0
https://github.com/leah/PullToRefresh                      0     0        0
https://github.com/brajeshwar/grid                         0     0        0
https://github.com/nanotech/jellybeans.vim                 0     0        0
https://github.com/arachnys/cabot                          0     0        0
https://github.com/mobile-shell/mosh                       0     0        0
https://github.com/mbbx6spp/7languages7weeks               0     0        0
https://github.com/alixander/PyScribe                      0     0        0
https://github.com/mdenil/dropout                          0     0        0
https://github.com/technoweenie/twitter-node               0     0        0
https://github.com/GRAAL-Research/PAC-Bayes_sam...         0     0        0
https://github.com/machawk1/archivability                  0     0        0
https://github.com/rjpower/loony                           0     0        0
https://github.com/recoilphp/recoil                        0     0        0
https://github.com/quirkey/static_model                    0     0        0
https://github.com/Xyl2k/TSA-Travel-Sentry-mast...         0     0        0
https://github.com/codysoyland/jquery-cookie               0     0        0
https://github.com/zeit/

In [516]:
str_recs[(str_recs==1).all(axis=1)]

Empty DataFrame
Columns: [lmcinnes, cchi, rushter]
Index: []

In [517]:
str_recs[str_recs.sum(axis=1)>1]

lmcinnes  cchi  rushter
https://github.com/rasbt/python-machine-learnin...         0     1        1
https://github.com/prakhar1989/awesome-courses             0     1        1
https://github.com/rasbt/pattern_classification            0     1        1
https://github.com/DrSkippy/Data-Science-45min-...         0     1        1
https://github.com/numenta/nupic                           0     1        1
https://github.com/kjw0612/awesome-rnn                     0     1        1
https://github.com/airbnb/aerosolve                        0     1        1
https://github.com/ogrisel/parallel_ml_tutorial            0     1        1
https://github.com/ChristosChristofidis/awesome...         0     1        1
https://github.com/PredictionIO/PredictionIO               0     1        1
https://github.com/mwaskom/seaborn                         1     0        1
https://github.com/okulbilisim/awesome-datascience         0     1        1